export const actionAccounts = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_CURRENT_INITIAL: 'GET_CURRENT_INITIAL',
    GET_CURRENT_REQUEST: 'GET_CURRENT_REQUEST',
    GET_CURRENT_SUCCESS: 'GET_CURRENT_SUCCESS',
    GET_CURRENT_FAILURE: 'GET_CURRENT_FAILURE',

    UPDATE_ACCOUNT_DETAIL_REQUEST: 'UPDATE_ACCOUNT_DETAIL_REQUEST',
    UPDATE_ACCOUNT_DETAIL_SUCCESS: 'UPDATE_ACCOUNT_DETAIL_SUCCESS',
    UPDATE_ACCOUNT_DETAIL_FAILURE: 'UPDATE_ACCOUNT_DETAIL_FAILURE',

    GET_ACCOUNT_INITIAL: 'GET_ACCOUNT_INITIAL',
    GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',
};
