export const actionAccounts = {
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_CURRENT_INITIAL: 'GET_CURRENT_INITIAL',
    GET_CURRENT_REQUEST: 'GET_CURRENT_REQUEST',
    GET_CURRENT_SUCCESS: 'GET_CURRENT_SUCCESS',
    GET_CURRENT_FAILURE: 'GET_CURRENT_FAILURE',

    UPDATE_ACCOUNT_DETAIL_REQUEST: 'UPDATE_ACCOUNT_DETAIL_REQUEST',
    UPDATE_ACCOUNT_DETAIL_SUCCESS: 'UPDATE_ACCOUNT_DETAIL_SUCCESS',
    UPDATE_ACCOUNT_DETAIL_FAILURE: 'UPDATE_ACCOUNT_DETAIL_FAILURE',

    GET_ACCOUNT_INITIAL: 'GET_ACCOUNT_INITIAL',
    GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

    USER_ALL_REQUEST: 'USER_ALL_REQUEST',
    USER_ALL_SUCCESS: 'USER_ALL_SUCCESS',
    USER_ALL_FAILURE: 'USER_ALL_FAILURE',

    USER_SINGLE_REQUEST: 'USER_SINGLE_REQUEST',
    USER_SINGLE_SUCCESS: 'USER_SINGLE_SUCCESS',
    USER_SINGLE_FAILURE: 'USER_SINGLE_FAILURE',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',
    
    USER_UPDATE_ENTIRE_REQUEST: 'USER_UPDATE_ENTIRE_REQUEST',
    USER_UPDATE_ENTIRE_SUCCESS: 'USER_UPDATE_ENTIRE_SUCCESS',
    USER_UPDATE_ENTIRE_FAILURE: 'USER_UPDATE_ENTIRE_FAILURE',
};
