export const actionAuthentications = {
    SIGNUP_INITIAL: 'USERS_SIGNUP_INITIAL',
    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    LOGIN_INITIAL: 'USERS_LOGIN_INITIAL',
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',

    CONFIRM_REQUEST: 'USERS_CONFIRM_REQUEST',
    CONFIRM_SUCCESS: 'USERS_CONFIRM_SUCCESS',
    CONFIRM_FAILURE: 'USERS_CONFIRM_FAILURE',

    ASK_FORGET_INITIAL: 'USERS_ASK_FORGET_INITIAL',
    ASK_FORGET_REQUEST: 'USERS_ASK_FORGET_REQUEST',
    ASK_FORGET_SUCCESS: 'USERS_ASK_FORGET_SUCCESS',
    ASK_FORGET_FAILURE: 'USERS_ASK_FORGET_FAILURE',

    FORGET_INITIAL: 'USERS_FORGET_INITIAL',
    FORGET_REQUEST: 'USERS_FORGET_REQUEST',
    FORGET_SUCCESS: 'USERS_FORGET_SUCCESS',
    FORGET_FAILURE: 'USERS_FORGET_FAILURE',
};
