export const actionModals = {
    OPEN_ERROR: 'OPEN_ERROR',
    CLOSE_ERROR: 'CLOSE_ERROR',
    OPEN_LOGOUT: 'OPEN_LOGOUT',
    CLOSE_LOGOUT: 'CLOSE_LOGOUT',
    OPEN_TERMS: 'OPEN_TERMS',
    CLOSE_TERMS: 'CLOSE_TERMS'
}
